<?php 
$album = $this->album;

$title = 'Album information';
$this->headTitle($title);
?>

<h1><?php echo $title; ?></h1>

<div class="row">
    <div class="span4">
        <table class="table">
        <tr>
            <th>Artist</th>
            <td><?php echo $this->escapeHtml($album->artist); ?></td>
        </tr>
        <tr>
            <th>Title</th>
            <td><?php echo $this->escapeHtml($album->title); ?></td>
        </tr>

        <tr>
            <th></th>
            <td>

                <a href="<?php echo $this->url('album',
                    array('action'=>'edit', 'id' => $album->id));?>">Edit</a>
                <a href="<?php echo $this->url('album',
                    array('action'=>'delete', 'id' => $album->id));?>">Delete</a>
            </td>
        </tr>
        </table>
    </div>
</div>
